"""Stage 3: turn a snapshot into the source text of a typed model module.

``generate_module`` is a pure function — snapshot dict in, Python source out,
no file I/O and no network. :func:`write_module` is the thin wrapper that puts
the text on disk.

Generated classes are pure schema descriptors: one class per sObject, one
plain annotated class attribute per field, nothing dynamic (D7). If mypy and
Pylance cannot resolve every field statically, the product does not work — so
the generated output is checked by both in the test suite.
"""

import keyword
from pathlib import Path
from typing import Any

from soqlmodel.describe import SNAPSHOT_FORMAT_VERSION

# The one place a Salesforce type becomes a Python type. Keyed on the
# snapshot's "type" value — we do not store soapType (D3).
TYPE_MAP = {
    "string": "str",
    "textarea": "str",
    "phone": "str",
    "url": "str",
    "email": "str",
    "picklist": "str",
    "multipicklist": "str",
    "reference": "str",
    "id": "str",
    "encryptedstring": "str",
    "boolean": "bool",
    "int": "int",
    "double": "float",
    "currency": "float",
    "percent": "float",
    "date": "date",
    "datetime": "datetime",
    "time": "time",
}

# Unmapped Salesforce types degrade to this rather than raising: Salesforce
# adds types, and an unknown one should cost us static typing on that field,
# not the whole module. Compound types (address, location) land here by
# design — see the backlog.
FALLBACK_TYPE = "Any"

_DATETIME_NAMES = frozenset({"date", "datetime", "time"})

_HEADER = "# Generated by soqlmodel. Do not edit."


def python_type_for(salesforce_type: str) -> str:
    """Map one Salesforce field type to a Python type name."""
    return TYPE_MAP.get(salesforce_type, FALLBACK_TYPE)


def _check_identifier(name: str, what: str) -> None:
    if not name.isidentifier() or keyword.iskeyword(name):
        raise ValueError(
            f"{what} {name!r} is not a usable Python identifier; "
            "refusing to generate a module with a mangled name"
        )


def _imports_for(python_types: list[str]) -> list[str]:
    """Build only the imports the output actually uses.

    A module with no date fields must not import ``date``: an unused import is
    a ruff error in every generated file.
    """
    used = set(python_types)
    lines = []

    from_datetime = sorted(_DATETIME_NAMES & used)
    if from_datetime:
        lines.append(f"from datetime import {', '.join(from_datetime)}")

    if FALLBACK_TYPE in used:
        lines.append("from typing import Any")

    if lines:
        lines.append("")

    lines.append("from soqlmodel.fields import Field")
    return lines


def generate_module(snapshot: dict[str, Any]) -> str:
    """Render a snapshot as the source text of a typed model module.

    Fields keep snapshot order, which `build_snapshot` already sorted. Nothing
    time-varying is emitted, so regenerating an unchanged snapshot produces
    byte-identical text.

    Raises:
        ValueError: if the sObject or any field name is not a usable Python
            identifier. Mangling it silently would produce a model whose
            attribute names do not match the org.
    """
    sobject = snapshot["sobject"]
    _check_identifier(sobject, "sObject name")

    fields = snapshot.get("fields") or []
    for field in fields:
        _check_identifier(field["name"], "field name")

    python_types = [python_type_for(field.get("type", "")) for field in fields]

    lines = [
        _HEADER,
        f"# Org: {snapshot['org']}",
        f"# Snapshot format: {snapshot.get('format_version', SNAPSHOT_FORMAT_VERSION)}",
        "",
        *_imports_for(python_types),
        "",
        "",
        f"class {sobject}:",
    ]

    if not fields:
        lines.append("    pass")
    for field, python_type in zip(fields, python_types, strict=True):
        name = field["name"]
        soql_type = field.get("type", "")
        lines.append(f'    {name}: Field[{python_type}] = Field("{name}", "{soql_type}")')

    return "\n".join(lines) + "\n"


def write_module(snapshot: dict[str, Any], path: str | Path) -> Path:
    """Write :func:`generate_module`'s output to ``path``.

    LF and utf-8 are explicit for the same reason as `write_snapshot`: the
    platform must not get a vote in what bytes come out.
    """
    path = Path(path)
    path.write_text(generate_module(snapshot), encoding="utf-8", newline="\n")
    return path
