"""Stage 3: turn a snapshot into the source text of a typed model module.

``generate_module`` is a pure function — snapshot dict in, Python source out,
no file I/O and no network. :func:`write_module` is the thin wrapper that puts
the text on disk.

Generated classes are pure schema descriptors: one class per sObject, one
plain annotated class attribute per field, nothing dynamic (D7). If mypy and
Pylance cannot resolve every field statically, the product does not work — so
the generated output is checked by both in the test suite.
"""

import keyword
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from soqlmodel.describe import SNAPSHOT_FORMAT_VERSION
from soqlmodel.errors import GenerateError

# The one place a Salesforce type becomes a Python type. Keyed on the
# snapshot's "type" value — we do not store soapType (D3).
TYPE_MAP = {
    "string": "str",
    "textarea": "str",
    "phone": "str",
    "url": "str",
    "email": "str",
    "picklist": "str",
    "multipicklist": "str",
    "reference": "str",
    "id": "str",
    "encryptedstring": "str",
    "boolean": "bool",
    "int": "int",
    "double": "float",
    "currency": "float",
    "percent": "float",
    "date": "date",
    "datetime": "datetime",
    "time": "time",
}

# Unmapped Salesforce types degrade to this rather than raising: Salesforce
# adds types, and an unknown one should cost us static typing on that field,
# not the whole module. Compound types (address, location) land here by
# design — see the backlog.
FALLBACK_TYPE = "Any"

_DATETIME_NAMES = frozenset({"date", "datetime", "time"})

_HEADER = "# Generated by soqlmodel. Do not edit."

# Ruff and Black both default to 88, so this is the value that needs no
# configuration for most projects. Set `line_length` in soqlmodel.toml to
# match a formatter configured differently (D18).
DEFAULT_LINE_LENGTH = 88


def python_type_for(salesforce_type: str) -> str:
    """Map one Salesforce field type to a Python type name."""
    return TYPE_MAP.get(salesforce_type, FALLBACK_TYPE)


def _check_identifier(name: str, what: str) -> None:
    if not name.isidentifier() or keyword.iskeyword(name):
        raise GenerateError(
            f"{what} {name!r} is not a usable Python identifier; "
            "refusing to generate a module with a mangled name"
        )


def _imports_for(python_types: list[str]) -> list[str]:
    """Build only the imports the output actually uses.

    A module with no date fields must not import ``date``: an unused import is
    a ruff error in every generated file.
    """
    used = set(python_types)
    lines = []

    from_datetime = sorted(_DATETIME_NAMES & used)
    if from_datetime:
        lines.append(f"from datetime import {', '.join(from_datetime)}")

    if FALLBACK_TYPE in used:
        lines.append("from typing import Any")

    if lines:
        lines.append("")

    lines.append("from soqlmodel.fields import Field")
    return lines


def _field_lines(name: str, python_type: str, soql_type: str, line_length: int) -> list[str]:
    """Render one field, wrapping it if the one-liner would overflow.

    Two forms, and which one is used is the whole of SFM-10c:

        Name: Field[str] = Field("Name", "string")

        Commission_Attainment_Rolling_12M__c: Field[str] = Field(
            "Commission_Attainment_Rolling_12M__c",
            "picklist",
        )

    The wrapped form ends in a **magic trailing comma**, which is load-bearing
    rather than decorative. Ruff and Black both treat that comma as "the author
    wants this exploded" and leave the call alone at *any* line length. Without
    it a formatter collapses the call back onto one line whenever it fits,
    which is exactly the churn this is fixing — verified at 79, 88, 100 and
    120.

    So the wrapped form is stable everywhere, and the one-line form is stable
    for any formatter configured at or above ``line_length``. Matching
    ``line_length`` to the formatter therefore makes the output stable outright,
    which is why it is configurable rather than a constant (D18).
    """
    one_line = f'    {name}: Field[{python_type}] = Field("{name}", "{soql_type}")'
    if len(one_line) <= line_length:
        return [one_line]

    return [
        f"    {name}: Field[{python_type}] = Field(",
        f'        "{name}",',
        f'        "{soql_type}",',
        "    )",
    ]


def _class_lines(snapshot: dict[str, Any], line_length: int) -> tuple[list[str], list[str]]:
    """Render one class body. Returns its lines and the Python types it uses."""
    sobject = snapshot["sobject"]
    _check_identifier(sobject, "sObject name")

    fields = snapshot.get("fields") or []
    for field in fields:
        _check_identifier(field["name"], "field name")

    python_types = [python_type_for(field.get("type", "")) for field in fields]

    lines = [f"class {sobject}:"]
    if not fields:
        lines.append("    pass")
    for field, python_type in zip(fields, python_types, strict=True):
        lines.extend(_field_lines(field["name"], python_type, field.get("type", ""), line_length))

    return lines, python_types


def _sobject_key(snapshot: dict[str, Any]) -> tuple[str, str]:
    name = snapshot["sobject"]
    return (name.lower(), name)


def generate_combined_module(
    snapshots: Sequence[dict[str, Any]], line_length: int = DEFAULT_LINE_LENGTH
) -> str:
    """Render several snapshots as one module, one class per sObject.

    Classes are ordered by sObject name and imports are the union of what the
    classes actually use, so regenerating from unchanged snapshots produces
    byte-identical text no matter what order they arrive in.

    Raises:
        GenerateError: if an sObject or field name is not a usable Python
            identifier. Mangling it silently would produce a model whose
            attribute names do not match the org.
    """
    ordered = sorted(snapshots, key=_sobject_key)

    bodies = []
    used_types: list[str] = []
    for snapshot in ordered:
        lines, python_types = _class_lines(snapshot, line_length)
        bodies.append(lines)
        used_types.extend(python_types)

    # Several snapshots should share an org and a format; if they somehow do
    # not, say so in the header rather than silently picking one.
    orgs = sorted({snapshot["org"] for snapshot in ordered})
    versions = sorted(
        {snapshot.get("format_version", SNAPSHOT_FORMAT_VERSION) for snapshot in ordered}
    )

    lines = [
        _HEADER,
        f"# Org: {', '.join(orgs)}",
        f"# Snapshot format: {', '.join(str(version) for version in versions)}",
        "",
        *_imports_for(used_types),
    ]
    for body in bodies:
        lines.extend(["", "", *body])

    return "\n".join(lines) + "\n"


def generate_module(snapshot: dict[str, Any], line_length: int = DEFAULT_LINE_LENGTH) -> str:
    """Render one snapshot as the source text of a typed model module.

    Fields keep snapshot order, which `build_snapshot` already sorted. Nothing
    time-varying is emitted, so regenerating an unchanged snapshot produces
    byte-identical text.
    """
    return generate_combined_module([snapshot], line_length)


def _write(text: str, path: str | Path) -> Path:
    """LF and utf-8 are explicit for the same reason as `write_snapshot`: the
    platform must not get a vote in what bytes come out.
    """
    path = Path(path)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def write_module(
    snapshot: dict[str, Any], path: str | Path, line_length: int = DEFAULT_LINE_LENGTH
) -> Path:
    """Write :func:`generate_module`'s output to ``path``."""
    return _write(generate_module(snapshot, line_length), path)


def write_combined_module(
    snapshots: Sequence[dict[str, Any]],
    path: str | Path,
    line_length: int = DEFAULT_LINE_LENGTH,
) -> Path:
    """Write :func:`generate_combined_module`'s output to ``path``."""
    return _write(generate_combined_module(snapshots, line_length), path)
