import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

from soqlmodel.errors import GenerateError
from soqlmodel.generate import (
    FALLBACK_TYPE,
    TYPE_MAP,
    generate_module,
    python_type_for,
    write_module,
)


def make_snapshot(*fields: dict, sobject: str = "Account", org: str = "FULL Sandbox") -> dict:
    return {
        "format_version": 1,
        "org": org,
        "sobject": sobject,
        "fields": list(fields),
    }


def field(name: str, salesforce_type: str) -> dict:
    return {"name": name, "type": salesforce_type, "label": name}


# --- type mapping -----------------------------------------------------------


@pytest.mark.parametrize(
    ("salesforce_type", "expected"),
    [
        ("string", "str"),
        ("textarea", "str"),
        ("phone", "str"),
        ("url", "str"),
        ("email", "str"),
        ("picklist", "str"),
        ("multipicklist", "str"),
        ("reference", "str"),
        ("id", "str"),
        ("encryptedstring", "str"),
        ("boolean", "bool"),
        ("int", "int"),
        ("double", "float"),
        ("currency", "float"),
        ("percent", "float"),
        ("date", "date"),
        ("datetime", "datetime"),
        ("time", "time"),
    ],
)
def test_type_mapping(salesforce_type, expected):
    assert python_type_for(salesforce_type) == expected


@pytest.mark.parametrize("unknown", ["address", "location", "base64", "somethingNew", ""])
def test_unmapped_types_fall_back_to_any(unknown):
    # Salesforce adds types; an unknown one costs static typing on that field,
    # not the whole module.
    assert python_type_for(unknown) == FALLBACK_TYPE


def test_the_type_map_is_the_only_mapping():
    # Guards against a second mapping creeping in elsewhere in the module.
    assert set(TYPE_MAP.values()) == {"str", "bool", "int", "float", "date", "datetime", "time"}


def test_renders_a_field_with_its_salesforce_type_preserved():
    source = generate_module(make_snapshot(field("AnnualRevenue", "currency")))

    assert (
        '    AnnualRevenue: Field[float] = Field("AnnualRevenue", "currency")' in source
    )


def test_compound_types_render_as_any():
    source = generate_module(make_snapshot(field("BillingAddress", "address")))

    assert '    BillingAddress: Field[Any] = Field("BillingAddress", "address")' in source


# --- header and structure ---------------------------------------------------


def test_header_names_the_org_and_format():
    source = generate_module(make_snapshot(field("Name", "string"), org="Prod"))

    assert source.startswith("# Generated by soqlmodel. Do not edit.\n")
    assert "# Org: Prod\n" in source
    assert "# Snapshot format: 1\n" in source


def test_class_is_named_for_the_sobject():
    source = generate_module(make_snapshot(field("Name", "string"), sobject="Revenue__c"))

    assert "class Revenue__c:" in source


def test_a_snapshot_with_no_fields_still_produces_a_valid_class():
    source = generate_module(make_snapshot())

    assert "class Account:\n    pass\n" in source


def test_fields_keep_snapshot_order():
    source = generate_module(
        make_snapshot(field("Zeta", "string"), field("Alpha", "string"))
    )

    assert source.index("Zeta") < source.index("Alpha")


# --- conditional imports ----------------------------------------------------


def test_omits_the_date_import_when_no_field_needs_it():
    source = generate_module(make_snapshot(field("Name", "string")))

    assert "from datetime import" not in source
    assert "from typing import Any" not in source
    assert "from soqlmodel.fields import Field" in source


def test_imports_only_the_datetime_names_in_use():
    source = generate_module(
        make_snapshot(field("CreatedDate", "datetime"), field("Birthday", "date"))
    )

    assert "from datetime import date, datetime\n" in source
    assert "time" not in source.split("class ")[0].replace("datetime", "")


def test_imports_any_only_when_a_field_falls_back():
    with_fallback = generate_module(make_snapshot(field("BillingAddress", "address")))
    without = generate_module(make_snapshot(field("Name", "string")))

    assert "from typing import Any" in with_fallback
    assert "from typing import Any" not in without


def test_imports_time_when_a_time_field_is_present():
    source = generate_module(make_snapshot(field("OpenFrom", "time")))

    assert "from datetime import time\n" in source


# --- determinism ------------------------------------------------------------


def test_regeneration_is_byte_identical():
    snapshot = make_snapshot(
        field("Name", "string"), field("CreatedDate", "datetime"), field("Site", "address")
    )

    assert generate_module(snapshot) == generate_module(snapshot)


def test_output_contains_no_timestamp():
    source = generate_module(make_snapshot(field("Name", "string")))

    assert "202" not in source  # no year would survive determinism


def test_write_module_is_byte_identical_across_writes(tmp_path):
    snapshot = make_snapshot(field("Name", "string"))

    first = write_module(snapshot, tmp_path / "a.py").read_bytes()
    second = write_module(snapshot, tmp_path / "b.py").read_bytes()

    assert first == second
    assert b"\r\n" not in first


# --- identifier guard -------------------------------------------------------


@pytest.mark.parametrize("bad", ["class", "import", "None", "lambda", "def"])
def test_rejects_python_keywords_as_field_names(bad):
    with pytest.raises(GenerateError, match="not a usable Python identifier"):
        generate_module(make_snapshot(field(bad, "string")))


@pytest.mark.parametrize("bad", ["My Field", "field-name", "2ndPlace", "weiße.spalte", ""])
def test_rejects_non_identifier_field_names(bad):
    with pytest.raises(GenerateError, match="not a usable Python identifier"):
        generate_module(make_snapshot(field(bad, "string")))


def test_the_guard_names_the_offending_field():
    with pytest.raises(GenerateError, match="My Field"):
        generate_module(make_snapshot(field("My Field", "string")))


def test_rejects_an_unusable_sobject_name():
    with pytest.raises(GenerateError, match="sObject name"):
        generate_module(make_snapshot(field("Name", "string"), sobject="My Object"))


def test_does_not_silently_mangle():
    # Whatever else happens, a bad name must not turn into a plausible one.
    with pytest.raises(GenerateError):
        generate_module(make_snapshot(field("field-name", "string")))


# --- the generated code must survive the tools ------------------------------


FIXTURE = make_snapshot(
    field("Id", "id"),
    field("Name", "string"),
    field("AnnualRevenue", "currency"),
    field("NumberOfEmployees", "int"),
    field("IsDeleted", "boolean"),
    field("CreatedDate", "datetime"),
    field("LastActivityDate", "date"),
    field("BillingAddress", "address"),
)


def test_generated_output_is_valid_python():
    compile(generate_module(FIXTURE), "<generated>", "exec")


def test_generated_output_passes_ruff(tmp_path):
    path = write_module(FIXTURE, tmp_path / "models.py")

    result = subprocess.run(
        [sys.executable, "-m", "ruff", "check", str(path)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_generated_output_passes_mypy(tmp_path):
    # The product's central claim: a generated model type-checks. If this
    # fails, soqlmodel does not work.
    path = write_module(FIXTURE, tmp_path / "models.py")

    result = subprocess.run(
        [sys.executable, "-m", "mypy", "--strict", str(path)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_generated_fields_are_statically_resolvable(tmp_path):
    # Not just "mypy is silent" — mypy must see the field with its real type.
    path = tmp_path / "probe.py"
    path.write_text(
        generate_module(FIXTURE)
        + "\nreveal_type(Account.AnnualRevenue)\nreveal_type(Account.Nonexistent)\n",
        encoding="utf-8",
        newline="\n",
    )

    result = subprocess.run(
        [sys.executable, "-m", "mypy", str(path)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert 'Revealed type is "soqlmodel.fields.Field[float]"' in result.stdout
    assert 'has no attribute "Nonexistent"' in result.stdout


REPO_ROOT = Path(__file__).resolve().parents[1]


@pytest.mark.slow
def test_the_built_wheel_contains_py_typed(tmp_path):
    """py.typed must survive packaging, not just exist in the source tree.

    Without it the installed package is untyped under PEP 561: every generated
    Field resolves to Any and the library's whole premise is silently absent.
    mypy stays quiet about it, so nothing else in this suite would notice — and
    a packaging change could drop the marker at any time.
    """
    uv = shutil.which("uv")
    if uv is None:
        pytest.fail("uv is needed to build the wheel; this check must not be skipped")

    result = subprocess.run(
        [uv, "build", "--wheel", "--out-dir", str(tmp_path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr

    wheels = list(tmp_path.glob("*.whl"))
    assert len(wheels) == 1, f"expected one wheel, got {wheels}"

    with zipfile.ZipFile(wheels[0]) as wheel:
        names = wheel.namelist()

    assert "soqlmodel/py.typed" in names, f"py.typed missing from wheel; contents: {names}"
